In [1]:
import numpy as np


In [2]:
trainedfor = [[0,1,2,3,4,5,6,7,8], 
              [0,1,2,3,4,5,6,7,8],
              [5,6,7,8],
              [5,6,7,8],
              [3,5,8],
              [0,1,2,3,4,5,6,7,8],
              [3],
              [0,1,2,4,5,6,7,8],
              [1,2],
              [0,1,2,3,4,5,6,7,8],
              [0,1,2,3,4,5,6,7,8],
              [0,1,2,3,4,5,6,7,8],
              [0,1,2,3,4,5,6,7,8],
              [0,1,2,3,4,5,6,7,8]]

empFTE = [7,7,8,7,8,8,8,7,8,8,5,5,8,8]

In [3]:
grid = np.zeros((14,14))
grid[0][0:4] = -1
grid[0][11:14] = 8
grid[1][4:11] = 8
grid[2][4:11] = 7
grid[6][3:11] = 3
grid [7][5:7] = -1
grid

array([[-1., -1., -1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  8.,  8.,
         8.],
       [ 0.,  0.,  0.,  0.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0., -1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 

In [4]:
def employeeview (empID):
   return grid[empID]
def dayview (dayID):
   d = grid.transpose()
   return d[dayID]
dayview(7)[8]

0.0

In [5]:
def week1count (e):
   count = 0
   emp1w = grid[e][0:7]
   for x in emp1w:
      if x != 0:
         count += 1
   return count
def week2count (e):
   count = 0
   emp1w = grid[e][7:14]
   for x in emp1w:
      if x != 0:
         count += 1
   return count
def checkweek (e,d):
   if d < 7:
      if week1count(e) < 5:
        return True
   if d > 6:
      if week2count(e) < 5:
         return True
      else:
         return False
    

In [6]:
def countEmpShifts (empID):
   view = employeeview(empID)
   count = 0
   for x in view:
      if x > 0 or x == -1:
         count += 1
   return count

In [7]:
def AllEmpCount ():
   callEmpCount = []
   for x in range(14):
      c = countEmpShifts(x)
      callEmpCount.append(c)
   return callEmpCount
AllEmpCount()

[7, 7, 7, 0, 0, 0, 8, 2, 0, 0, 0, 0, 0, 0]

In [8]:
def notOverFTE (e):
   if AllEmpCount()[e] < empFTE[e]:
      return True
   # for x in range(len(s)):
   #    if s[x] <= empFTE[x]:
   #       return True
   return False

In [9]:
grid[[5]]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
def isTrainedFor ():
   val = []
   celllist = []
   for e in range(9):
      for x in employeeview(e):
         if x > 0:
            if x in trainedfor[e]:
               val.append("T")
            else:
               cell = f'emp={e},s={x}'
               celllist.append(cell)
               val.append("F")
         if x == 0:
            val.append("T")
   if val.count('F') == 0:
      return True
   else:
      return False, celllist
print(isTrainedFor())

True


In [11]:
def emptrained (e,s):
   if s in trainedfor[e]:
      return True
   else:
      return False

In [12]:
def countDayShifts (dayID):
   view = dayview(dayID)
   count = 0
   for x in view:
      if x > 0:
         count += 1
   return count

In [13]:
def cellswithShifts():
   count = 0
   for x in grid:
      for y in x:
         if y != 0:
            count += 1
   return count

In [14]:
def shiftnotonday (d,s):
   if s in dayview(d):
      return False
   return True

In [15]:
def noturnaround(e,d,s):
   if s>5 and d !=13:
      if grid[e][d+1] != 0:
         if grid[e][d+1] < 5:
            return False
   if s<4 and d !=0:
      if grid[e][d-1] !=0:
         if grid[e][d-1] > 5:
            return False
   return True

In [16]:
def isWeekendShift (d,s):
   if d in [0, 6,7,13]:
      if s == 4:
         return False
   return True

In [17]:
def solveCell (d,e,s):
   x = emptrained(e,s)
   y = notOverFTE(e)
   z = shiftnotonday(d,s)
   m = checkweek(e,d)
   n = noturnaround(e,d,s)
   o = isWeekendShift(d,s)
   if x == True:
      if y == True:
         if z == True:
            if m == True:
               if n == True:
                  if o == True:
                     grid[e][d]=s
   return False

## Recursive Execution x 7000

In [18]:
"""Run 20000 iterations of random possible shift assignments"""

x = 0
while x < 7000:
   d =np.random.randint(0,14)
   e = np.random.randint(0,14)
   s = np.random.randint(0,9)
   if grid[e][d] == 0 and notOverFTE(e) == True and noturnaround(e,d,s) == True:
      #print (grid[e][d],e,d,s,shiftnotonday(d,s),notUnderFTE(e))
      solveCell(d,e,s)
      x +=1
   else:
      x +=1
print(AllEmpCount(),cellswithShifts())
print(grid)

[7, 7, 8, 7, 8, 8, 8, 7, 8, 8, 5, 5, 8, 8] 102
[[-1. -1. -1. -1.  0.  0.  0.  0.  0.  0.  0.  8.  8.  8.]
 [ 0.  0.  0.  0.  8.  8.  8.  8.  8.  8.  8.  0.  0.  0.]
 [ 0.  7.  0.  0.  7.  7.  7.  7.  7.  7.  7.  0.  0.  0.]
 [ 0.  8.  7.  6.  0.  0.  0.  0.  6.  0.  5.  6.  0.  7.]
 [ 3.  0.  8.  5.  5.  5.  0.  0.  5.  0.  0.  5.  0.  3.]
 [ 0.  3.  1.  4.  6.  0.  0.  1.  0.  0.  0.  3.  4.  6.]
 [ 0.  0.  0.  3.  3.  3.  3.  3.  3.  3.  3.  0.  0.  0.]
 [ 8.  0.  2.  1.  0. -1. -1.  0.  0.  5.  4.  0.  0.  0.]
 [ 0.  1.  0.  0.  1.  2.  1.  0.  1.  2.  2.  0.  2.  0.]
 [ 2.  0.  4.  8.  0.  0.  6.  6.  0.  6.  0.  4.  0.  1.]
 [ 0.  0.  6.  0.  0.  4.  0.  0.  4.  0.  6.  0.  0.  5.]
 [ 0.  2.  0.  2.  0.  0.  5.  0.  0.  1.  0.  2.  0.  0.]
 [ 5.  4.  0.  7.  4.  0.  2.  0.  2.  4.  0.  0.  5.  0.]
 [ 6.  0.  3.  0.  0.  6.  0.  2.  0.  0.  1.  1.  3.  2.]]


In [19]:
for x in grid.transpose():
   y = np.setxor1d(range(9),x)
   z = np.intersect1d(y,range(9))
   z


## PRINTING RESULTS

In [23]:
print("NCMC CPHT SCHEDULE | 2 WEEK")
print("-"*60)
new = ""
for i in range(len(grid)):
   myrow = ""
   for x in grid[i]:
      if x == 8:
         myrow += "N  "
      if x == 7:
         myrow += "3  "
      if x== 6:
         myrow += "EP "
      if x == 5:
         myrow += "EI "
      if x == 4:
         myrow += "S  "
      if x == 3:
         myrow += "7P "
      if x == 2:
         myrow += "7C "
      if x == 1:
         myrow += "MI "
      if x == 0:
         myrow += ".  "
      if x == -1:
         myrow += "pto"
   myrow += "| EMPLOYEE_NAME"
   new += myrow + "\n"
new += "-"*65

shift_titles = 'MI 7C 7P S EI EP 3 N'.split(' ')
print(new)
print(cellswithShifts())
for d in range (14):
   for s in range(9):
      if shiftnotonday(d,s):
         print (d, shift_titles[s-1])

   

NCMC CPHT SCHEDULE | 2 WEEK
------------------------------------------------------------
ptoptoptopto.  .  .  .  .  .  .  N  N  N  | EMPLOYEE_NAME
.  .  .  .  N  N  N  N  N  N  N  .  .  .  | EMPLOYEE_NAME
.  3  .  .  3  3  3  3  3  3  3  .  .  .  | EMPLOYEE_NAME
.  N  3  EP .  .  .  .  EP .  EI EP .  3  | EMPLOYEE_NAME
7P .  N  EI EI EI .  .  EI .  .  EI .  7P | EMPLOYEE_NAME
.  7P MI S  EP .  .  MI .  .  .  7P S  EP | EMPLOYEE_NAME
.  .  .  7P 7P 7P 7P 7P 7P 7P 7P .  .  .  | EMPLOYEE_NAME
N  .  7C MI .  ptopto.  .  EI S  .  .  .  | EMPLOYEE_NAME
.  MI .  .  MI 7C MI .  MI 7C 7C .  7C .  | EMPLOYEE_NAME
7C .  S  N  .  .  EP EP .  EP .  S  .  MI | EMPLOYEE_NAME
.  .  EP .  .  S  .  .  S  .  EP .  .  EI | EMPLOYEE_NAME
.  7C .  7C .  .  EI .  .  MI .  7C .  .  | EMPLOYEE_NAME
EI S  .  3  S  .  7C .  7C S  .  .  EI .  | EMPLOYEE_NAME
EP .  7P .  .  EP .  7C .  .  MI MI 7P 7C | EMPLOYEE_NAME
-----------------------------------------------------------------
102
0 MI
0 S
0 3
1 EI
1 EP
2 EI
4