In [1139]:
import numpy as np


In [1140]:
grid = np.zeros((14,14))
grid[0][0:4] = -1
grid[1][4:11] = 8
grid [7][5:7] = -1
grid

array([[-1., -1., -1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0., -1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 

In [1141]:
def employeeview (empID):
   return grid[empID]
def dayview (dayID):
   d = grid.transpose()
   return d[dayID]
dayview(7)[8]

0.0

In [1142]:
def countEmpShifts (empID):
   view = employeeview(empID)
   count = 0
   for x in view:
      if x > 0:
         count += 1
   return count

In [1143]:
def AllEmpCount ():
   callEmpCount = []
   for x in range(14):
      c = countEmpShifts(x)
      callEmpCount.append(c)
   return callEmpCount
AllEmpCount()

[0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [1144]:
empFTE = [7,7,8,7,8,8,8,7,8,8,5,5,8,8]
def notUnderFTE (e):
   if AllEmpCount()[e] < empFTE[e]:
      return True
   # for x in range(len(s)):
   #    if s[x] <= empFTE[x]:
   #       return True
   return False

In [1145]:
notUnderFTE(2)

True

In [1146]:
trainedfor = [[0,1,2,3,4,5,6,7,8],
              [0,1,2,3,4,5,6,7,8],
              [5,6,7,8],
              [5,6,7,8],
              [3,5,8],
              [5,8],
              [0,1,2,4,5,6,7,8],
              [1,2],
              [0,1,2,3,4,5,6,7,8],
              [0,1,2,3,4,5,6,7,8],
              [0,1,2,3,4,5,6,7,8],
              [0,1,2,3,4,5,6,7,8],
              [0,1,2,3,4,5,6,7,8],
              [0,1,2,3,4,5,6,7,8]]

In [1147]:
grid[[5]]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [1148]:
def isTrainedFor ():
   val = []
   celllist = []
   for e in range(9):
      for x in employeeview(e):
         if x > 0:
            if x in trainedfor[e]:
               val.append("T")
            else:
               cell = f'emp={e},s={x}'
               celllist.append(cell)
               val.append("F")
         if x == 0:
            val.append("T")
   if val.count('F') == 0:
      return True
   else:
      return False, celllist
print(isTrainedFor())

True


In [1149]:
def emptrained (e,s):
   if s in trainedfor[e]:
      return True
   else:
      return False

In [1150]:
def countDayShifts (dayID):
   view = dayview(dayID)
   count = 0
   for x in view:
      if x > 0:
         count += 1
   return count

In [1151]:
def cellswithShifts():
   count = 0
   for x in grid:
      for y in x:
         if y != 0:
            count += 1
   return count

In [1152]:
def shiftnotonday (d,s):
   if s in dayview(d):
      return False
   return True

In [1153]:
def noturnaround(e,d,s):
   if s>5 and d !=13:
      if grid[e][d+1] != 0:
         if grid[e][d+1] < 5:
            return False
   return True

In [1154]:
def solveCell (d,e,s):
   x = emptrained(e,s)
   y = notUnderFTE(e)
   z = shiftnotonday(d,s)
   if x == True:
      if y == True:
         if z == True:
            grid[e][d]=s
   return False

In [1155]:
x = 0
while x < 10000:
   d =np.random.randint(0,14)
   e = np.random.randint(0,14)
   s = np.random.randint(0,9)
   if grid[e][d] == 0 and notUnderFTE(e) == True and noturnaround(e,d,s) == True:
      #print (grid[e][d],e,d,s,shiftnotonday(d,s),notUnderFTE(e))
      solveCell(d,e,s)
      x +=1
   else:
      x +=1
print(AllEmpCount(),cellswithShifts())
print(grid)

[7, 7, 8, 7, 8, 4, 8, 7, 8, 8, 5, 5, 8, 8] 104
[[-1. -1. -1. -1.  1.  1.  1.  5.  0.  4.  6.  6.  0.  0.]
 [ 0.  0.  0.  0.  8.  8.  8.  8.  8.  8.  8.  0.  0.  0.]
 [ 6.  6.  7.  7.  7.  0.  0.  0.  0.  5.  0.  0.  5.  5.]
 [ 8.  0.  8.  5.  0.  6.  0.  7.  0.  0.  0.  8.  0.  6.]
 [ 5.  0.  5.  0.  5.  5.  3.  0.  3.  0.  0.  0.  3.  3.]
 [ 0.  5.  0.  0.  0.  0.  5.  0.  0.  0.  0.  5.  0.  8.]
 [ 1.  0.  4.  0.  0.  7.  0.  0.  1.  6.  7.  7.  8.  0.]
 [ 0.  0.  1.  2.  0. -1. -1.  1.  2.  1.  2.  1.  0.  0.]
 [ 0.  1.  0.  6.  2.  2.  7.  0.  6.  0.  0.  0.  2.  7.]
 [ 3.  0.  2.  0.  0.  4.  0.  0.  4.  7.  0.  3.  1.  2.]
 [ 7.  8.  0.  8.  0.  0.  0.  0.  0.  3.  0.  0.  7.  0.]
 [ 0.  0.  0.  4.  3.  0.  4.  0.  0.  0.  1.  0.  0.  1.]
 [ 0.  7.  6.  3.  0.  0.  6.  0.  7.  0.  5.  4.  0.  4.]
 [ 4.  4.  0.  0.  6.  3.  2.  0.  5.  2.  0.  0.  6.  0.]]


In [1156]:
for x in grid.transpose():
   y = np.setxor1d(range(9),x)
   print (y)


[-1.  2.]
[-1.  2.  3.]
[-1.  3.]
[-1.  1.]
[4.]
[-1.]
[-1.]
[2. 3. 4. 6.]
[]
[]
[3. 4.]
[2.]
[4.]
[]


In [1157]:
new = ""
for i in range(len(grid)):
   myrow = ""
   for x in grid[i]:
      if x == 8:
         myrow += "N   "
      if x == 7:
         myrow += "3   "
      if x== 6:
         myrow += "EP  "
      if x == 5:
         myrow += "EI  "
      if x == 4:
         myrow += "S   "
      if x == 3:
         myrow += "7P  "
      if x == 2:
         myrow += "7C  "
      if x == 1:
         myrow += "MI  "
      if x == 0:
         myrow += ".   "
      if x == -1:
         myrow += "PTO "
   new += myrow + "\n"
print(new)

   

PTO PTO PTO PTO MI  MI  MI  EI  .   S   EP  EP  .   .   
.   .   .   .   N   N   N   N   N   N   N   .   .   .   
EP  EP  3   3   3   .   .   .   .   EI  .   .   EI  EI  
N   .   N   EI  .   EP  .   3   .   .   .   N   .   EP  
EI  .   EI  .   EI  EI  7P  .   7P  .   .   .   7P  7P  
.   EI  .   .   .   .   EI  .   .   .   .   EI  .   N   
MI  .   S   .   .   3   .   .   MI  EP  3   3   N   .   
.   .   MI  7C  .   PTO PTO MI  7C  MI  7C  MI  .   .   
.   MI  .   EP  7C  7C  3   .   EP  .   .   .   7C  3   
7P  .   7C  .   .   S   .   .   S   3   .   7P  MI  7C  
3   N   .   N   .   .   .   .   .   7P  .   .   3   .   
.   .   .   S   7P  .   S   .   .   .   MI  .   .   MI  
.   3   EP  7P  .   .   EP  .   3   .   EI  S   .   S   
S   S   .   .   EP  7P  7C  .   EI  7C  .   .   EP  .   



In [1158]:
# TO DO: Make sure shift counts DNE 4 per each 7 day block
# Needed Shifts for weekend