In [1437]:
import numpy as np


In [1438]:
grid = np.zeros((14,14))
grid[0][0:4] = -1
grid[1][4:11] = 8
grid[2][4:11] = 7
grid[6][3:11] = 3
grid [7][5:7] = -1
grid

array([[-1., -1., -1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0., -1., -1.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 

In [1439]:
def employeeview (empID):
   return grid[empID]
def dayview (dayID):
   d = grid.transpose()
   return d[dayID]
dayview(7)[8]

0.0

In [1440]:
def countEmpShifts (empID):
   view = employeeview(empID)
   count = 0
   for x in view:
      if x > 0 or x == -1:
         count += 1
   return count

In [1441]:
def AllEmpCount ():
   callEmpCount = []
   for x in range(14):
      c = countEmpShifts(x)
      callEmpCount.append(c)
   return callEmpCount
AllEmpCount()

[4, 7, 7, 0, 0, 0, 8, 2, 0, 0, 0, 0, 0, 0]

In [1442]:
empFTE = [7,7,8,7,8,8,8,7,8,8,5,5,8,8]
def notUnderFTE (e):
   if AllEmpCount()[e] < empFTE[e]:
      return True
   # for x in range(len(s)):
   #    if s[x] <= empFTE[x]:
   #       return True
   return False

In [1443]:
notUnderFTE(2)

True

In [1444]:
trainedfor = [[0,1,2,3,4,5,6,7,8],
              [0,1,2,3,4,5,6,7,8],
              [5,6,7,8],
              [5,6,7,8],
              [3,5,8],
              [0,1,2,3,4,5,6,7,8],
              [3],
              [0,1,2,4,5,6,7,8],
              [1,2],
              [0,1,2,3,4,5,6,7,8],
              [0,1,2,3,4,5,6,7,8],
              [0,1,2,3,4,5,6,7,8],
              [0,1,2,3,4,5,6,7,8],
              [0,1,2,3,4,5,6,7,8]]

In [1445]:
grid[[5]]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [1446]:
def isTrainedFor ():
   val = []
   celllist = []
   for e in range(9):
      for x in employeeview(e):
         if x > 0:
            if x in trainedfor[e]:
               val.append("T")
            else:
               cell = f'emp={e},s={x}'
               celllist.append(cell)
               val.append("F")
         if x == 0:
            val.append("T")
   if val.count('F') == 0:
      return True
   else:
      return False, celllist
print(isTrainedFor())

True


In [1447]:
def emptrained (e,s):
   if s in trainedfor[e]:
      return True
   else:
      return False

In [1448]:
def countDayShifts (dayID):
   view = dayview(dayID)
   count = 0
   for x in view:
      if x > 0:
         count += 1
   return count

In [1449]:
def cellswithShifts():
   count = 0
   for x in grid:
      for y in x:
         if y != 0:
            count += 1
   return count

In [1450]:
def shiftnotonday (d,s):
   if s in dayview(d):
      return False
   return True

In [1451]:
def noturnaround(e,d,s):
   if s>5 and d !=13:
      if grid[e][d+1] != 0:
         if grid[e][d+1] < 5:
            return False
   if s<4 and d !=0:
      if grid[e][d-1] !=0:
         if grid[e][d-1] > 5:
            return False
   return True

In [1452]:
def solveCell (d,e,s):
   x = emptrained(e,s)
   y = notUnderFTE(e)
   z = shiftnotonday(d,s)
   if x == True:
      if y == True:
         if z == True:
            grid[e][d]=s
   return False

In [1453]:
x = 0
while x < 10000:
   d =np.random.randint(0,14)
   e = np.random.randint(0,14)
   s = np.random.randint(0,9)
   if grid[e][d] == 0 and notUnderFTE(e) == True and noturnaround(e,d,s) == True:
      #print (grid[e][d],e,d,s,shiftnotonday(d,s),notUnderFTE(e))
      solveCell(d,e,s)
      x +=1
   else:
      x +=1
print(AllEmpCount(),cellswithShifts())
print(grid)

[7, 7, 8, 7, 5, 8, 8, 7, 8, 8, 5, 5, 8, 8] 99
[[-1. -1. -1. -1.  2.  0.  0.  0.  2.  0.  0.  0.  0.  8.]
 [ 0.  0.  0.  0.  8.  8.  8.  8.  8.  8.  8.  0.  0.  0.]
 [ 8.  0.  0.  0.  7.  7.  7.  7.  7.  7.  7.  0.  0.  0.]
 [ 6.  8.  8.  0.  6.  0.  0.  5.  0.  0.  0.  0.  6.  5.]
 [ 5.  0.  0.  0.  0.  5.  0.  0.  0.  5.  5.  0.  5.  0.]
 [ 7.  0.  4.  5.  0.  0.  5.  6.  0.  4.  0.  5.  0.  3.]
 [ 0.  0.  0.  3.  3.  3.  3.  3.  3.  3.  3.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1. -1.  4.  0.  0.  4.  6.  8.  6.]
 [ 1.  0.  0.  2.  1.  1.  1.  1.  0.  0.  1.  1.  0.  0.]
 [ 4.  5.  3.  0.  0.  6.  4.  2.  0.  6.  0.  8.  0.  0.]
 [ 0.  0.  6.  7.  4.  0.  0.  0.  0.  0.  6.  0.  1.  0.]
 [ 0.  7.  0.  0.  0.  0.  0.  0.  1.  1.  0.  3.  3.  0.]
 [ 3.  3.  2.  8.  5.  0.  0.  0.  5.  0.  0.  7.  0.  1.]
 [ 0.  2.  5.  6.  0.  0.  6.  0.  6.  0.  2.  4.  0.  4.]]


In [1454]:
for x in grid.transpose():
   y = np.setxor1d(range(9),x)
   z = np.intersect1d(y,range(9))
   z


In [1455]:
print("NCMC CPHT SCHEDULE | 2 WEEK")
print("-"*60)
new = ""
for i in range(len(grid)):
   myrow = ""
   for x in grid[i]:
      if x == 8:
         myrow += "N  "
      if x == 7:
         myrow += "3  "
      if x== 6:
         myrow += "EP "
      if x == 5:
         myrow += "EI "
      if x == 4:
         myrow += "S  "
      if x == 3:
         myrow += "7P "
      if x == 2:
         myrow += "7C "
      if x == 1:
         myrow += "MI "
      if x == 0:
         myrow += ".  "
      if x == -1:
         myrow += "pto"
   myrow += "| EMPLOYEE_NAME"
   new += myrow + "\n"
new += "-"*65

print(new)
print(cellswithShifts())

   

NCMC CPHT SCHEDULE | 2 WEEK
------------------------------------------------------------
ptoptoptopto7C .  .  .  7C .  .  .  .  N  | EMPLOYEE_NAME
.  .  .  .  N  N  N  N  N  N  N  .  .  .  | EMPLOYEE_NAME
N  .  .  .  3  3  3  3  3  3  3  .  .  .  | EMPLOYEE_NAME
EP N  N  .  EP .  .  EI .  .  .  .  EP EI | EMPLOYEE_NAME
EI .  .  .  .  EI .  .  .  EI EI .  EI .  | EMPLOYEE_NAME
3  .  S  EI .  .  EI EP .  S  .  EI .  7P | EMPLOYEE_NAME
.  .  .  7P 7P 7P 7P 7P 7P 7P 7P .  .  .  | EMPLOYEE_NAME
.  .  .  .  .  ptoptoS  .  .  S  EP N  EP | EMPLOYEE_NAME
MI .  .  7C MI MI MI MI .  .  MI MI .  .  | EMPLOYEE_NAME
S  EI 7P .  .  EP S  7C .  EP .  N  .  .  | EMPLOYEE_NAME
.  .  EP 3  S  .  .  .  .  .  EP .  MI .  | EMPLOYEE_NAME
.  3  .  .  .  .  .  .  MI MI .  7P 7P .  | EMPLOYEE_NAME
7P 7P 7C N  EI .  .  .  EI .  .  3  .  MI | EMPLOYEE_NAME
.  7C EI EP .  .  EP .  EP .  7C S  .  S  | EMPLOYEE_NAME
-----------------------------------------------------------------
99
