In [940]:
import numpy as np


In [941]:
grid = np.zeros((9,14))

grid

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [942]:
def employeeview (empID):
   return grid[empID]
def dayview (dayID):
   d = grid.transpose()
   return d[dayID]
dayview(7)[8]

0.0

In [943]:
def countEmpShifts (empID):
   view = employeeview(empID)
   count = 0
   for x in view:
      if x > 0:
         count += 1
   return count

In [944]:
def AllEmpCount ():
   callEmpCount = []
   for x in range(9):
      c = countEmpShifts(x)
      callEmpCount.append(c)
   return callEmpCount
AllEmpCount()

[0, 0, 0, 0, 0, 0, 0, 0, 0]

In [945]:
empFTE = [7,7,8,7,8,8,8,7,5]
def notUnderFTE (e):
   if AllEmpCount()[e] < empFTE[e]:
      return True
   # for x in range(len(s)):
   #    if s[x] <= empFTE[x]:
   #       return True
   return False

In [946]:
notUnderFTE(2)

True

In [947]:
trainedfor = [[0,1,2,3,4,5,6,7,8],
              [0,1,2,3,4,5,6,7,8],
              [5,6,7,8],
              [5,6,7,8],
              [3,5,8],
              [5,8],
              [0,1,2,4,5,6,7,8],
              [1,2],
              [0,1,2,3,4,5,6,7,8]]

In [948]:
grid[[5]]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [949]:
def isTrainedFor ():
   val = []
   celllist = []
   for e in range(9):
      for x in employeeview(e):
         if x > 0:
            if x in trainedfor[e]:
               val.append("T")
            else:
               cell = f'emp={e},s={x}'
               celllist.append(cell)
               val.append("F")
         if x == 0:
            val.append("T")
   if val.count('F') == 0:
      return True
   else:
      return False, celllist
print(isTrainedFor())

True


In [950]:
def emptrained (e,s):
   if s in trainedfor[e]:
      return True
   else:
      return False

In [951]:
def countDayShifts (dayID):
   view = dayview(dayID)
   count = 0
   for x in view:
      if x > 0:
         count += 1
   return count

In [952]:
def cellswithShifts():
   count = 0
   for x in grid:
      for y in x:
         if y != 0:
            count += 1
   return count

In [953]:
def shiftnotonday (d,s):
   if s in dayview(d):
      return False
   return True

In [954]:
def noturnaround(e,d,s):
   if s>5 and d !=13:
      if grid[e][d+1] != 0:
         if grid[e][d+1] < 5:
            return False
   return True

In [955]:
def solveCell (d,e,s):
   x = emptrained(e,s)
   y = notUnderFTE(e)
   z = shiftnotonday(d,s)
   if x == True:
      if y == True:
         if z == True:
            grid[e][d]=s
   return False

In [958]:
x = 0
while x < 10000:
   d =np.random.randint(0,14)
   e = np.random.randint(0,9)
   s = np.random.randint(0,9)
   if grid[e][d] == 0 and notUnderFTE(e) == True and noturnaround(e,d,s) == True:
      #print (grid[e][d],e,d,s,shiftnotonday(d,s),notUnderFTE(e))
      solveCell(d,e,s)
      x +=1
   else:
      x +=1
print(AllEmpCount(),cellswithShifts())
print(grid)

[7, 7, 8, 7, 8, 8, 8, 7, 5] 65
[[3. 0. 0. 4. 1. 1. 0. 7. 2. 0. 0. 0. 8. 0.]
 [5. 2. 2. 5. 0. 0. 0. 0. 8. 0. 0. 7. 4. 0.]
 [7. 7. 0. 6. 0. 8. 8. 0. 0. 7. 5. 0. 0. 6.]
 [0. 6. 7. 0. 0. 0. 5. 0. 6. 0. 8. 0. 6. 5.]
 [8. 8. 0. 0. 3. 5. 0. 3. 0. 0. 3. 0. 5. 3.]
 [0. 5. 5. 8. 5. 0. 0. 5. 5. 5. 0. 5. 0. 0.]
 [0. 0. 1. 2. 8. 0. 0. 2. 4. 8. 1. 8. 0. 0.]
 [2. 0. 0. 1. 0. 2. 0. 1. 0. 0. 2. 2. 1. 0.]
 [0. 0. 8. 0. 6. 0. 0. 0. 1. 0. 0. 1. 0. 7.]]
